### ISSUE TITLE
Issues with machines in complab

### ISSUE THREAD

**Issue by cdondrup** [LCAS/teaching#1]
This is from observation in Comp Lab B so it might be different in Comp Lab C:

* Ubuntu 12.04 **32-bit** installed
* lcas.lincoln.ac.uk is not reachable
 * Not able to download packages from build server

This will have to be fixed/confirmed working before the start of the module.

**Comment by cdondrup** [comment]
Update from CompLab C:
- Machines have hydro installed on Ubuntu 14.04. Since this is not fully supported I think it should be changed.
- Indigo repositories are not set-up in sources.list

Installation of the turtlebot simulator is therefore not possible

**Comment by marc-hanheide** [comment]
Hang on... how _can_ hydro at all by installed??? I think Matt must have messed up the update. But students do have sudo access, right. So we could tell them HOW to install everything? 
But we should also set up Matt's master image correctly, as he is going to wipe all machines again next week (after gam jam) I understand. Can you go and find him to install everything on the master image (including enabling LCAS sources)?

**Comment by cdondrup** [comment]
Will do, just testing the whole simulator thing on one of the machines.

**Comment by cdondrup** [comment]
Indigo and uol-cmp3641m are now installed on the master image. Matt will create an image tomorrow and wipe all the machines next week. For the first workshop they have to install everything themselves. Takes about 30-45 minutes to complete.

**Comment by marc-hanheide** [comment]
Thanks... we shall keep them entertained nonetheless ;-)
