### ISSUE TITLE
Possible diffdrive kinematics math error

### ISSUE THREAD

**Issue by wc-s** [LCAS/teaching#18]
In cmp3641m-code-fragments/kinematics_diffdrive.py

The forward kinematics should perhaps be this:

a = (c_l - c_r) / (2 * robot_radius)

instead of the current code:

a = (c_l - c_r) / robot_radius

**Comment by marc-hanheide** [comment]
Thanks @wc-s why do you think so? The radius is already half the diameter. Also, that would mean the inverse kinematics also being incorrect as with the currently implementation it is indeed the inverse of the forwards kinematics, e.g.:

```
# inverse kinematics:

(w_l, w_r) = inverse_kinematics(2.0, 1.0)
print "w_l = %f,\tw_r = %f" % (w_l, w_r)

# this should give us again the desired values:
(v, a) = forward_kinematics(w_l, w_r)
print "v = %f,\ta = %f" % (v, a)
```

prints 

```
v = 2.000000,	a = 1.000000
```

again, as expected.

**Comment by wc-s** [comment]
Ha good point, sorry I should have ran the test script first before voicing my questions.

I do actually wonder if there might be an error in the inverse kinematics.

I don't quite understand why, in the inverse_kinematics, we have the divide-by-2 in:
```
c_l = v + (robot_radius * a) / 2
c_r = v - (robot_radius * a) / 2
```

(I take c_l and c_r to mean the wheel velocities in terms of displacement along the ground in m/s.)

(I take it that in this robot's example, robot_radius is the same as wheel_separation.)

Given the original script's test input of (v = 0, a = 1), I think the robot should rotate in-place, with an orientation change of 1 rad every 1 second. This should mean that, every 1 second, the two wheels would each travel 1 meter (orientation_change * robot_radius = 1 * 1 = 1) along the circumference of the circle drawn by the in-place rotation. This suggests that c_l and c_r should be 1 m/s. However, when running the original python script, the outputs are:

```
w_l = 0.500000,	w_r = -0.500000
v = 0.000000,	a = 1.000000
```

(Since wheel_radius = 1, the w_l and the w_r here are the same as the c_l and c_r.)

Wouldn't the wheel velocities obtained this way mean that our robot is only rotating in-place half as fast as it should?

**Comment by marc-hanheide** [comment]
Right! Well spotted, I think I do agree with you on this one. I indeed, apparently, used the wheel separation instead of radius in my thinking... 

So, would you agree this making more sense then:


# Forward and inverse Kinematics for Turtlebot

We define two functions `forward_kinemantics` and `inverse_kinematics` respectively. They allow to convert from wheel speeds to robot motion and from desired robot motion to wheel speeds.

* `v` denotes the linear velocity of the robot
* `a` denotes the angular velocity of the robot
* `w_l` is the angular velocity of the left wheel
* `w_r` is the angular velocity of the right wheel

unit are `m` for geometry, `m/s` for linear velocity and `rad/s` for angular velocity


```python
import math
#from geometry_msgs.msg import Twist


# some estimates for the robot gemorty
#wheel_radius = 0.05 # 5 cm radius of wheel
#robot_radius = 0.25  # 25 cm radio of base
wheel_radius = 1 # 5 cm radius of wheel
robot_radius = 1  # 25 cm radio of base


# computing the forward kinematics for a differential drive
def forward_kinematics(w_l, w_r):
    c_l = wheel_radius * w_l
    c_r = wheel_radius * w_r
    v = (c_l + c_r) / 2
    a = (c_l - c_r) / (2 * robot_radius)
    return (v, a)


# computing the inverse kinematics for a differential drive
def inverse_kinematics(v, a):
    c_l = v + (robot_radius * a) 
    c_r = v - (robot_radius * a) 
    w_l = c_l / wheel_radius
    w_r = c_r / wheel_radius
    return (w_l, w_r)


```


```python
# try out forward kinematics, both wheels turning at `2pi rad/s` (one full turn per second)

(v, a) = forward_kinematics(2*math.pi, 2*math.pi)
print "v = %f,\ta = %f" % (v, a)

```

    v = 6.283185,	a = 0.000000



```python
# try out forward kinematics, one wheel turning at `2pi rad/s` (one full turn per second), the other `-2pi rad/s`

(v, a) = forward_kinematics(2*math.pi, -2*math.pi)
print "v = %f,\ta = %f" % (v, a)

```

    v = 0.000000,	a = 6.283185



```python
# inverse kinematics:

(w_l, w_r) = inverse_kinematics(1.0, 1.0)
print "w_l = %f,\tw_r = %f" % (w_l, w_r)

# this should give us again the desired values:
(v, a) = forward_kinematics(w_l, w_r)
print "v = %f,\ta = %f" % (v, a)

```

    w_l = 2.000000,	w_r = 0.000000
    v = 1.000000,	a = 1.000000

I have opened a pull request with the change: #19 If you agree, I'll merge it to correct this mistake. Thanks!

**Comment by wc-s** [comment]
Hi. Yea, those equations for forward and inverse kinematics are what I have.

I am only a master's student who wandered onto this page because I'm doing something involving diff. drive, though. So uh while I think my math is correct, I'm not like an authority or anything haha.

I guess there might be one other small thing. As far as I can tell from trying out TurtleBot in Gazebo, a positive angular velocity rotates the robot counter-clockwise, vice versa. So the plus/minus sign for the left/right wheels might need to be switched. But maybe the you guys are using robots with different conventions.

**Comment by marc-hanheide** [comment]
yeah... that's something I already noticed as well. But forgot about it. Thanks.
