### ISSUE TITLE
Assignment mazes

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/teaching#35]
- [x] make 3 solvable mazes
- [x] add blue markers on best path
- [x] make 3 launch files for the 3 mazes
- [x] document in wiki (new page) on how to launch
- [x] release new version after PR test and merge
- [x] develop a simple solution for the assignment (separate, not in this repository)

**Comment by francescodelduchetto** [comment]
is the wiki page okay? https://github.com/LCAS/teaching/wiki/Launching-the-test-mazes-for-the-assignment

**Comment by marc-hanheide** [comment]
Released 1.0.4 based on #36
