### ISSUE TITLE
[cmp3641m] Add coloured blobs in simulation

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/teaching#9]
We should put a coloured blob (a box roughly 15x7x10 (w x d x h) cm) on top of each simulated robot.

**Comment by cdondrup** [comment]
It's quite easy to have two boxes with the same colour. Different coloured boxes might be pretty hard since I would need a separate model for each turtlebot. Since a turtlebot cannot see itself this shouldn't be a problem imo

**Comment by marc-hanheide** [comment]
We are happy with what we have.
